/* Generated By:JavaCC: Do not edit this line. ParserDLVConstants.java */
package parser;

public interface ParserDLVConstants {

  int EOF = 0;
  int AND = 6;
  int OR = 7;
  int NOT = 8;
  int NOT_EQUAL = 9;
  int COMPARISON = 10;
  int EQUAL = 11;
  int OPERATOR = 12;
  int MINUS = 13;
  int STRONG = 14;
  int WEAK = 15;
  int COLON = 16;
  int DOT = 17;
  int ORB = 18;
  int CRB = 19;
  int OSB = 20;
  int CSB = 21;
  int OBB = 22;
  int CBB = 23;
  int UNKNOWN = 24;
  int INT = 25;
  int MAXINT = 26;
  int FUNCTION_NAME = 27;
  int CONSTANT = 28;
  int NUMBER = 29;
  int VARIABLE = 30;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\",\"",
    "\"v\"",
    "\"not\"",
    "\"!=\"",
    "<COMPARISON>",
    "\"=\"",
    "<OPERATOR>",
    "\"-\"",
    "\":-\"",
    "\":~\"",
    "\":\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"_\"",
    "\"#int\"",
    "\"#maxint\"",
    "<FUNCTION_NAME>",
    "<CONSTANT>",
    "<NUMBER>",
    "<VARIABLE>",
  };

}
